repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--manifest-path', 'src/Simulation/qdk_sim_rs/Cargo.toml', '--']
      - id: cargo-check
        args: ['--manifest-path', 'src/Simulation/qdk_sim_rs/Cargo.toml', '--']
      - id: clippy
        args: ['--manifest-path', 'src/Simulation/qdk_sim_rs/Cargo.toml', '--']

